timeout = 5
domains = ["blog.hezebin.com", "localhost:8080"]

[[uris]]
    paths = ["/api/*"]
    endpoint = "blog"
    auth = false
    desc = "博客无需鉴权的 API"
    priority = 0
    [uris.rewrite]
        "/api" = "/"


[[uris]]
    paths = ["/api/user/*"]
    endpoint = "user-center"
    auth = false
    desc = "用户中心 API"
    priority = 1
    [uris.rewrite]
    "/api" = "/"