service_name = "api-gateway"
port = 8080

[logger]
    level = "debug"
    filename = "go-template-ddd.log"

[redis]
    addr = "127.0.0.1:6379"
    password = "root"

[[endpoints]]
    name = "user-service"
    host = "http://127.0.0.1:9000"

[[endpoints]]
    name = "blog"
    host = "http://127.0.0.1:9001"