service_name = "api-gateway"
port = 8080

[logger]
    level = "debug"
    filename = "api-gateway.log"

[redis]
   addrs = ["127.0.0.1:6379"]
   password = "root"

[[endpoints]]
    name = "blog"
    host = "http://blog-service"

[[endpoints]]
    name = "user-center"
    host = "http://user-center-service"