service_name = "api-gateway"
port = 8080

[logger]
    level = "debug"
    filename = "api-gateway.log"

[redis]
    addrs = ["redis-sts-0.redis.default:7000", "redis-sts-1.redis.default:7000", "redis-sts-2.redis.default:7000"]
    password = "HZB183318a."

[[endpoints]]
    name = "blog"
    host = "http://blog-service"

[[endpoints]]
    name = "user-center"
    host = "http://user-center-service"