timeout = 5
domains = ["*blog.hezebin.com"]

[headers]
"Endpoint" = "blog"

[[uris]]
paths = ["/blog/*"]
endpoint = "blog"
auth = true
desc = "博客服务"
priority = 0
[uris.rewrite]
"/blog" = "/"

[[uris]]
paths = ["/blog-service/*"]
endpoint = "blog"
auth = true
desc = "博客服务"
priority = 0
[uris.rewrite]
"/blog" = "/"


