timeout = 5
domains = ["*user-service.hezebin.com"]

[headers]
    "Endpoint" = "user-service"

[[uris]]
    paths = ["/user/*"]
    endpoint = "user-service"
    auth = true
    desc = "用户服务"
    priority = 0
    [uris.rewrite]
        "/user-service" = "/"

[[uris]]
    paths = ["/user-service/*"]
    endpoint = "user-service"
    auth = true
    desc = " 用户服务"
    priority = 0
    [uris.rewrite]
        "/user-service" = "/"


